import {
  GENDER_OPTIONS,
  INTEREST_TAG_OPTIONS,
  INTENTIONS_OPTIONS,
  KINK_OPTIONS,
  LOOKING_FOR_OPTIONS,
  ORIENTATION_OPTIONS,
  PRONOUNS_OPTIONS,
  ROLE_OPTIONS,
} from '@/lib/constants'

export const PROFILE_OPTION_DEFAULTS = {
  lookingFor: LOOKING_FOR_OPTIONS,
  intentions: INTENTIONS_OPTIONS,
  gender: GENDER_OPTIONS,
  pronouns: PRONOUNS_OPTIONS,
  orientation: ORIENTATION_OPTIONS,
  interests: INTEREST_TAG_OPTIONS,
  kinks: KINK_OPTIONS,
  roles: ROLE_OPTIONS,
} as const
